### ISSUE TITLE
problem when pasting numbers with decimalCharacterAlternative

### ISSUE THREAD

**Issue by connexion2000** [BobKnothe/autoNumeric#426] opened 2017-03-30 10:59 UTC
### Expected behavior
after pasting f.e. 56.45 to autonumeric field, it should format to 56,45

### Actual behavior
Pasting formats to 5 645. Decimal character is omitted.

### Link to live example (ie. [Codepen](http://codepen.io/pen/))
https://jsfiddle.net/txc31x61/1/

please try to paste 56.45 to autonumeric field

### version
2.0.10

**Comment by AlexandreBonneau** [comment] 2017-03-30 11:16
Hi @connexion2000, this is a duplicate of https://github.com/BobKnothe/autoNumeric/issues/424, which detail why this happens.

It's not clear exactly if we'll change the current behavior, depending of the complexity of the PR (if any).

**Closed by AlexandreBonneau** 2017-03-30 11:16 UTC
