### ISSUE TITLE
Problem with initial formatting of whole numbers

### ISSUE THREAD

**Issue by manukura** [BobKnothe/autoNumeric#119] opened 2015-02-08 00:25 UTC
I find when I call the init method with aForm: true and the initial value is a whole number, there are no decimal places included in the result.

For example, when the initial value is new BigDecimal (1000) I would expect the result displayed as 1,000.00 but instead I am getting 1,000

If I enter the same number manually, the formatting correctly adds the decimal places

Also, if aSign is specified, it is not populated on the initial format

**Comment by BobKnothe** [comment] 2015-02-08 03:23
Manukura,

Please post an example of jsFiddle showing the "init" method and the 
HTML 5 data and options passed.

Let me know the AN version you are using.

Thanks,

Bob

**Comment by manukura** [comment] 2015-02-08 21:47
Hi Bob,

Apologies … excellent suggestion to do the jsFiddle.  Much to my surprise my example worked there, so I delved into the problem more.

It turns out that when Spring is performing the binding to populate my jsp it is formatting the string.  By default, it will insert the thousands separators but no decimal if the number is whole.  Say my number is 1000 spring will output 1,000

When I have auto numeric initialise the field I can either say it is pre-formatted so get 1,000 which is not what I want or I can tell auto numeric to format it and get 10.00.  Neither is what I want, but the problem is solvable by changing the spring binding.

Here is a jsFiddle to demonstrate the difficulty with formatting the 1,000.  http://jsfiddle.net/75jkegws/

**Comment by BobKnothe** [comment] 2015-02-09 01:59
Manukura,

Not familiar enough with Spring to be helpful. Is the comma treated as 
the decimal separator?

When I (hopefully) get time to officially launch v2.0 I would like to 
document your issue/solution if you are willing to share!

Anyway glad it worked out for you - please close the issue if you are 
satisfied.

Best regards,

Bob

**Comment by BobKnothe** [comment] 2015-02-15 15:58
Manukura,

Please re-open if you find the issue is in AN.

Bob

**Closed by BobKnothe** 2015-02-15 15:58 UTC
