### ISSUE TITLE
Pressing delete adds unwanted zeros

### ISSUE THREAD

**Issue by ContextSwitch** [BobKnothe/autoNumeric#262] opened 2016-11-15 14:54 UTC
Pressing the delete key adds unwanted zeros to the number we're displaying in a text field. The settings we are using are:

mDec:'2', 
mRound:'D', 
lZero:'deny'

**Comment by AlexandreBonneau** [comment] 2016-12-08 08:16
Hi @ContextSwitch, could you please provide a live example (ie. codepen) of the problem, what you expect, what you get instead, and the steps to reproduce it?
Thanks!

**Comment by AlexandreBonneau** [comment] 2016-12-30 02:03
Since I was not able to reproduce the *'bug'*, and there is no more activity on this issue, I'm closing it.

Feel free to reopen it if you feel we missed something.

**Closed by AlexandreBonneau** 2016-12-30 02:03 UTC
Labels: Bug, Marked for deletion, Need user input
