### ISSUE TITLE
i try format vtigercrm integer field

### ISSUE THREAD

**Issue by YnievesDotNet** [BobKnothe/autoNumeric#402] opened 2017-02-17 19:22 UTC
When i try format integer inputs in vtiger 6 fields, added a zero prefix, for example, 123456 then is shown as 0.123.456, and when i try edit, vtiger say, input integer value

Thanks,

this is my options
```js
const field = {
    digitGroupSeparator        : '.',
    decimalCharacter           : ',',
    decimalCharacterAlternative: '.',
    decimalPlacesOverride      : '0',
    formatOnPageLoad           : true,
    unformatOnSubmit           : true
};
```

Yoinier.

**Comment by AlexandreBonneau** [comment] 2017-02-17 19:33
Hello @YnievesDotNet, I'm unfortunately not sure how to reproduce the problem.
Could you please provide a codepen or any other live example we could edit?

Also, which version of autoNumeric are you using?

**Comment by YnievesDotNet** [comment] 2017-02-17 20:01
```
var numericInputs = [
    "copropiedades_tks_vlorprimaact", "copropiedades_tks_siniestralid", "copropiedades_tks_edificioarea",
    "copropiedades_tks_cotedificioa", "cf_786", "cf_788", "cf_790", "cf_792", "cf_794", "cf_796", "cf_798",
    "cf_800", "cf_802", "cf_804", "cf_806", "cf_808", "cf_810", "cf_812", "cf_814", "cf_816", "cf_818",
    "cf_820", "cf_822", "cf_824", "cf_826", "cf_828", "cf_830", "cf_832", "cf_834", "cf_838", "cf_836", "cf_840"
];

const copropiedadesField = {
    digitGroupSeparator        : '.',
    decimalCharacter           : ',',
    decimalCharacterAlternative: '.',
    decimalPlacesOverride      : '0',
    formatOnPageLoad           : true,
    unformatOnSubmit           : true
};

numericInputs.forEach(function (input) {
    $('#Copropiedades_editView_fieldName_' + input).autoNumeric("init", copropiedadesField);
    $('#Copropiedades_detailView_fieldValue_' + input + ' > span.value').autoNumeric("init", copropiedadesField);
});
```

this is my js

**Comment by YnievesDotNet** [comment] 2017-02-17 20:03
![captura de pantalla de 2017-02-17 15-02-28](https://cloud.githubusercontent.com/assets/1451485/23081307/32876040-f522-11e6-9968-a411e1fd279f.png)

**Comment by AlexandreBonneau** [comment] 2017-02-17 20:35
Well, we do not have any link to fiddle with this unfortunately, so everything I'll tell you is just a conjecture;
It looks like your crm is trying to enforce pure JS integers in those input fields, which means it does not like the *string* autoNumeric generate.
As you can see [in the doc](https://github.com/BobKnothe/autoNumeric#on-which-elements-can-it-be-used), autoNumeric cannot be used on `<input>` of the type `number`.

A live example would help a lot more than screenshots though, since we would then be able to check the code and debug it directly!

Also, I see that in your inputs (which I assume are initialized with aN), the formatting is correct (without any leading `0`).
Couldn't the problem be in your code when trying to copy that value elsewhere?

Where do you get the data `0.123.456` you are displaying on the page from?

**Comment by AlexandreBonneau** [comment] 2017-02-23 06:30
@YnievesDotNet, on gitter you seemed to have solved your problem.
If that's the case, please close this issue, thanks!

*On our end, we usually close the issues that have the `Need user input` tag if we do not get an answer during a month.*

**Comment by AlexandreBonneau** [comment] 2017-03-17 19:23
Due to inactivity, I'm closing this issue considering it resolved.

If that's not the case, feel free to re-open it!

**Closed by AlexandreBonneau** 2017-03-17 19:23 UTC
Labels: Need user input
