### ISSUE TITLE
Not compatible with jQuery 2

### ISSUE THREAD

**Issue by joan** [BobKnothe/autoNumeric#105] opened 2014-11-14 11:27 UTC
Used with jQuery 2, every focus make a jQuery "too much recursion" error.
(Great plug-in though!)
Thanks

**Comment by j-schumann** [comment] 2015-01-23 18:52
Seems to work now, with jQuery 2.1.0, see http://jsfiddle.net/33fsykqz/1/
Don't know if anything was changed/fixed in autoNumeric or in a new version of jQuery. Maybe the updated compatibility could be added to the changelog/website?

**Comment by BobKnothe** [comment] 2015-01-23 20:26
Glad it's working.

Would need a lot more info to narrow down a possible cause (browser 
version, jQuery version and if it being run locally or on a server).

If every thing is OK please close the issue(s)

**Closed** 2015-01-24 14:15 UTC

**Comment by joan** [comment] 2015-01-27 13:15
Didn't test it again, but great if it's solved.
Infos in case : jQuery v2.1.1 on Fx & Chrome, locally & on a server.

**Comment by guaycuru** [comment] 2015-01-27 16:58
Happening to me as well, on Firefox 35.0.1, not on Chrome. jQuery 2.1.1, being run on a localhost server (so not really locally, nor really on a remote server).
The error pops up on console when I click on the input that has autoNumeric on.

**Comment by BobKnothe** [comment] 2015-01-28 01:51
Just tested with Firefox 35.0.1 on the above JS Fiddle http://jsfiddle.net/33fsykqz/1/ and I do not get any error messages.

**Comment by guaycuru** [comment] 2015-01-28 13:51
I wasn't able to make it reproducible on jsFiddle, but I was able to isolate it on a HTML file hosted on my server: http://guaycuru.net/BugAuto.htm

**Comment by BobKnothe** [comment] 2015-01-28 15:46
Felipe,
 
I am not getting any error message - tried on Chrome, FF & IE.
 
What does the message say?
 
Bob
 
--------- Original Message --------- Subject: Re: [autoNumeric] Not compatible with jQuery 2 (#105)

**Comment by guaycuru** [comment] 2015-01-28 17:26
too much recursion
	

...ject"==typeof a||"function"==typeof a?h[i.call(a)]||"object":typeof a},globalEva...

Here's a screenshot: http://guaycuru.net/BugAuto.png

The message usually appears only after I click on the input.

**Comment by BobKnothe** [comment] 2015-01-28 18:28
I would like to try to duplicate - can you please provide info on OS & Browser version.

I am puzzled why I am not getting the error on FF (win7) from my side?

**Comment by guaycuru** [comment] 2015-01-28 18:44
I'm using Windows 7 Professional x64 and Firefox 35.0.1

**Comment by BobKnothe** [comment] 2015-01-28 21:21
Felipe,
 
That is exactly the same and I am not receiving the error.
 
Perplexing. 
 
Bob
 
--------- Original Message --------- Subject: Re: [autoNumeric] Not compatible with jQuery 2 (#105)

**Comment by guaycuru** [comment] 2015-01-29 11:56
Hmm turns out I had a couple of extensions enabled on FIrefox I'd forgot
about, so I disabled one by one, and found the one that's causing it:
FireBug 1.4.1 -> https://addons.mozilla.org/pt-br/firefox/addon/firequery/
>
>
So looks like there's some kind of incompatibility between AutoNumeric and
that FireBug extension (since that error is not triggered by anything else,
nor is it triggered when FireBug is disabled)...

**Comment by peterboccia** [comment] 2015-01-29 13:29
An extension in chrome is causing a lot of error in my environment, you would have had to notice it long time ago. The error were really strange.
Good to hear that it's solved and there's nothing wrong in the plugin.

**Comment by BobKnothe** [comment] 2015-01-29 13:39
Thank you for your methodical investigation.

 I am using Fire Bug 2.0.7 and the error does not occur.

I have not experienced any issues in Chrome -  but I only have a couple of extensions.

**Comment by peterboccia** [comment] 2015-01-29 13:49
No the extension error is not related to autoNumeric but I generate a javascript error, that someone could confuse with an error inside its own page.
So always check twice for the error message.

**Comment by guaycuru** [comment] 2015-01-29 14:23
Please note that the extension name is FireQuery, not FireBug, I updated
that accordingly...

The new text should read:

Hmm turns out I had a couple of extensions enabled on FIrefox I'd forgot
about, so I disabled one by one, and found the one that's causing it:
FireQuery 1.4.1 -> https://addons.mozilla.org/pt-br/firefox/addon/firequery/
So looks like there's some kind of incompatibility between AutoNumeric and
that FireQuery extension (since that error is not triggered by anything
else, nor is it triggered when FireQuery is disabled)...

Notice that the error only appears when the FireBug console is open and I
click on the input.
