### ISSUE TITLE
The package.json "postinstall" task does not find the target file when not using the dev dependencies

### ISSUE THREAD

**Issue by leider** [BobKnothe/autoNumeric#367] opened 2017-01-25 21:28 UTC
I use autonumeric from a node app. Therefore my deps are loaded with npm. I use node 6.5 and inside my `package.json` autonumeric is referenced. npm install the fails with an error when trying to run the `postinstall` script.

Please fix as this makes the current version unusable for my project.

**Comment by leider** [comment] 2017-01-25 21:30
One more thing: the `package.json`is here: https://github.com/softwerkskammer/Agora/blob/master/package.json

Old version of autonumeric, of course. :)

**Comment by AlexandreBonneau** [comment] 2017-01-26 00:31
Hello @leider , what is the error message exactly?
Do you have a way so we can reproduce it?
Have you tried with autoNumeric 2.0.0? It just has been released!

**Comment by AlexandreBonneau** [comment] 2017-01-26 00:55
I tried cloning your repo and ran `npm install`, but instantly stumbled upon another error :
```text
» npm install
npm WARN engine punycode@2.1.0: wanted: {"node":">=6"} (current: {"node":"4.7.2","npm":"1.4.21"})
npm WARN optional dep failed, continuing fsevents@1.0.17
 
> phantomjs-prebuilt@2.1.14 install /home/user/dev/Agora/node_modules/phantomjs-prebuilt
> node install.js

module.js:327
    throw err;
    ^

Error: Cannot find module 'is-property'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/user/dev/Agora/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object
-property/index.js:1:80)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! phantomjs-prebuilt@2.1.14 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.14 install script.
npm ERR! This is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.8.0-2-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/user/dev/Agora
npm ERR! node -v v4.7.2
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/user/dev/Agora/npm-debug.log
npm ERR! not ok code 0
```

**Comment by leider** [comment] 2017-01-26 06:43
Yes it's v2 final. 

You need to run the stuff on node 6.5 or maybe higher.

**Comment by AlexandreBonneau** [comment] 2017-01-26 08:09
Ok so, without any error message, I modified my Debian testing installation since it does not currently provide a higher node version than 4.7.2., so here is what I did :
```bash
git clone https://github.com/softwerkskammer/Agora.git && cd Agora
yarn install # fails with "error punycode@2.1.0: The engine "node" is incompatible with this module. Expected version ">=6"."
```
then I ugraded node with :
```bash
npm install -g n
n stable
ln -sf /usr/local/n/versions/node/7.4.0/bin/node /usr/bin/node
mv /usr/bin/nodejs /usr/bin/nodejs_original
ln -s /usr/bin/node /usr/bin/nodejs
```
...and finally `nodejs --version` return `v7.4.0`.

Now, when I try to `npm install` your project, I get this error message :
```text
npm install
module.js:472
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /usr/share/npm/bin/npm-cli.js:18:11
    at Object.<anonymous> (/usr/share/npm/bin/npm-cli.js:86:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

**Comment by leider** [comment] 2017-01-28 15:22
I'ver created a showcase with node versions 4,6,7: 
https://travis-ci.org/leider/autonumeric-showcase

It fails with any of these as you may see.

**Comment by leider** [comment] 2017-01-28 15:26
The problem is that you call a script from postinstall. Your script will definitely NOT WORK on people's installations that only "depend" your module. :)

Easy fix: just remove the postinstall section.

**Comment by leider** [comment] 2017-01-28 15:27
btw, codes is there: https://github.com/leider/autonumeric-showcase

**Comment by AlexandreBonneau** [comment] 2017-01-29 08:10
Thank you for providing a clear example on how this fails @leider!

Removing the `postinstall` line would perhaps resolve this specific case, but that would also reverse the fix done in that [commit](https://github.com/BobKnothe/autoNumeric/commit/0a79bb90be47dc4302856ed04889a05eea6b3139).

This line was added to workaround the fact that `yarn` (which is what we use instead of `npm` for a few weeks now) was not calling `install.js` in the `phantomjs-prebuilt` package correctly on installation.

We'll have to find a way to make it work in both cases.

**Comment by leider** [comment] 2017-01-29 12:54
1.) Sounds like a (bad) joke:
- you insert a postinstall script inside `package.json`, a file from the `npm` project
- this leads to the fact that it can not be used from `npm` anymore

2.) What do I as a "client" or "user" of your software care about `phantomjs`. Maybe I do not even want to have that installed. - I guess you want to run some tests. You could move the call to before test execution.

3.) This sounds like a weird workaround. You are blaming `yarn` for something wrong. Did you dig deeper in that direction? - I mean, requiring `phantom-prebuild` should lead to a working prerequisite.  After all this is not a very exotic setup.

4.) Until then, please change the readme to clearly state that requiring v2.0.0 from within npm will not work.

**Comment by AlexandreBonneau** [comment] 2017-01-30 09:46
I'll dismiss the last angry comment that miss the point, and rely only on the first exchanges which were cordial and semi-productive ;)

I pushed a fix that prevent the script to fail, even when you do not have the dev dependencies.

Hopefully, [karma-phantomjs-launcher](https://github.com/karma-runner/karma-phantomjs-launcher/issues/120) and/or [ya](https://github.com/yarnpkg/yarn/issues/1538)[rn](https://github.com/yarnpkg/yarn/issues/1016) will fix that bug and we'll be able to remove this hack!

**Closed by AlexandreBonneau** 2017-01-30 09:46 UTC
Labels: Bug, Dev, In progress

**Comment by jsmarsch** [comment] 2017-01-30 20:00
Hi Alexandre:  Has the change that fixed this been released to as an npm module?  I tried to install today, and I am getting the same errors as the OP.  npm is attempting to pull version 2.0.3.  Is that the correct package?

**Comment by jsmarsch** [comment] 2017-01-30 20:18
Hi Alexandre:  just FYI:  I tried updating my machine to the latest version of node/latest npm for my O/S (windows, node: 6.9.4, npm 4.1.2), 

I also noticed that the release has been updated to 2.0.4, but it's still erring.

**Comment by AlexandreBonneau** [comment] 2017-01-30 20:31
Hi @jsmarsch,

What error message are you seeing exactly?

On my end I tested to create new projects by using `yarn` and `npm` like that :
```sh
mkdir /tmp/test-an && cd /tmp/test-an
yarn init #name 'test-an', `enter` for all other info
yarn add autonumeric
```
and
```sh
mkdir /tmp/test-an && cd /tmp/test-an
npm init #name 'test-an', `enter` for all other info
npm install autonumeric
```
and it worked for both.

Did I miss something else?

The last version is currently v2.0.4 (somehow the `dist` folder got erased before I published 2.0.3, whoops ;)).

Let's fix this once and for all so we can go back hacking v3.0.0 :)

**Comment by AlexandreBonneau** [comment] 2017-01-30 21:41
Apparently this fix only worked for Unix-based environments, but not for Windows.
I'll keep this issue closed since @jsmarsch opened a windows-specific one.

Any follow-up regarding this issue (if it concern Windows), should be done in #384.

**Comment by jsmarsch** [comment] 2017-01-30 21:42
Hi Alexandre:

I'm on a Windows machine, so I tried your tests 2 ways:  once with the Windows Command interpreter (cmd.exe), and once with gitbash, which is a bash console installed with git for windows.

In both cases, I got the same error.  Here's what I got:

```
427 error Windows_NT 6.1.7601
428 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jmarsch\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "autonumeric"
429 error node v6.9.4
430 error npm  v4.1.2
431 error code ELIFECYCLE
432 error autonumeric@2.0.4 postinstall: `test -e node_modules/phantomjs-prebuilt/install.js && node node_modules/phantomjs-prebuilt/install.js; true`
432 error Exit status 1
433 error Failed at the autonumeric@2.0.4 postinstall script 'test -e node_modules/phantomjs-prebuilt/install.js && node node_modules/phantomjs-prebuilt/install.js; true'.
433 error Make sure you have the latest version of node.js and npm installed.
433 error If you do, this is most likely a problem with the autonumeric package,
433 error not with npm itself.
433 error Tell the author that this fails on your system:
433 error     test -e node_modules/phantomjs-prebuilt/install.js && node node_modules/phantomjs-prebuilt/install.js; true
433 error You can get information on how to open an issue for this project with:
433 error     npm bugs autonumeric
433 error Or if that isn't available, you can get their info via:
433 error     npm owner ls autonumeric
433 error There is likely additional logging output above.
434 verbose exit [ 1, true ]
```

**Comment by jsmarsch** [comment] 2017-01-30 21:48
One additional note on the error info above:  I did run as an admin, and, at least after running the commands, there was no node_modules folder , so either the rmdir command succeeded, or the directory never got created.

**Comment by AlexandreBonneau** [comment] 2017-01-30 21:49
Thanks for giving more details about this error @jsmarsch.
Would it be possible to move those comments to the other issue please?

**Comment by jsmarsch** [comment] 2017-01-30 21:49
Sure -- sorry!

**Comment by leider** [comment] 2017-01-30 22:14
FYI: this works now. Thanks a lot!

P.S.: I haven't been angry.
