### ISSUE TITLE
Conflict with OnSelect event

### ISSUE THREAD

**Issue by jorgechoypernia** [BobKnothe/autoNumeric#114] opened 2015-01-15 23:45 UTC
Hi.

First, many thanks for such a great plugIn. I am currently working autonumeric which can accept currency and percentage (alternate).

I am using the select event for some internal logic as user might want to highlight the text in order to replace it with a new number with a percentage or currency symbol or without symbol at all.

What happen is that the "onSelect" event is always being triggered when the user type something. This does not happen without the autonumeric plug in. Why the OnSelect is always triggering?

Can you please advise how to solve this issue? Also, I would also like to donate as this plugin has saved my life for other projects :) 

Below my javascript example. I am currently using asp.net with updatePanels... Thanks

$('input.lagUnitFormat').on('select', function (event) {
    if (isTextSelected(document.getElementById(event.target.id), 'hfLagUnit')) {
        varLeadLagSelectFlag = true;
        currenLeadLagInput = event.target.id;
    } else {
        varLeadLagSelectFlag = false;
        currenLeadLagInput = '';
    }
});

function isTextSelected(input, lagLeadUnitHfId) {
    var startPos = input.selectionStart;
    var endPos = input.selectionEnd;
   var doc = document.selection;

   if (doc && doc.createRange().text == $('#' + input.id).autoNumeric('get')) 
       return true;
   } else if (!doc && input.value.substring(startPos, endPos).replace($('#' + getId(lagLeadUnitHfId)).val(), '') == $('#' + input.id).autoNumeric('get')) {
       return true;
   }
   return false;
}

**Comment by BobKnothe** [comment] 2015-01-16 17:29
I will try and look at this this weekend. 

 
Robert (Bob) Knothe

**Comment by BobKnothe** [comment] 2015-01-17 16:01
Jorge,

Did some quick tests and could not get the "select" event to fire when 
entering numbers. It does fire when multiple characters are highlighted.

I used the following code for my tests.

$('input').on('select keydown keypress keyup', function (event) {
        console.log(event);
});

Does you code select multiple characters?

If I miss understand you please give me more details.

Donations are always appreciated.

Bob

**Comment by jorgechoypernia** [comment] 2015-01-18 14:33
Hi Bob, Many thanks for replying me back,

This behaviour is only happening with my IE11 browser. I have tested it with chrome and mozilla and it seems to work ok.

I suspect that the reason is a conflict with the scriptmanager of the .net framework. I am using something call update panel that is something like an ajax mechanism from microsoft (I hate it now, but this was initially implemented in the system years ago). 

I am going to keep trying to identify the issue. In the event that I cannot find it, would you accept/receive an example page or maybe an URL link where you can reproduce the issue?

Again, many thanks.

By the way, I have made a donation from your official site. Thanks

J. Choy.

**Comment by BobKnothe** [comment] 2015-01-18 19:10
Jorge,

If you can not isolate the issue I would be glad to take a look - just 
be patient, the next couple weeks are busy for me.

I is much easier for me to trace this when you post a URL versus me 
trying to create a page.

Best regards and thank your the donation.

Bob

**Comment by BobKnothe** [comment] 2015-02-08 18:23
Jorge,

Hope you found the cause.

I am closing this but you can always reopen if needed.

Bob

**Closed by BobKnothe** 2015-02-08 18:23 UTC
