### ISSUE TITLE
automatically doubling numbers when formatted.

### ISSUE THREAD

**Issue by fmiboy** [BobKnothe/autoNumeric#186] opened 2015-12-23 14:51 UTC
version 1.9.42
When number is formatted after entering 5 or more digits it will auto insets copy of the entered number making number double.

example: 12,345,123,456 (entered 12345 and 6 but it doubled and added 6 at the end.)

details: on Android, with jquery and jquerymobile.

anyone has this issue?

**Comment by BobKnothe** [comment] 2015-12-23 16:25
You are the first to report. 

Please post a fiddle. 

 
Robert (Bob) Knothe

**Comment by fmiboy** [comment] 2015-12-24 07:52
Hi Robert,

I don't have fiddle... And it occurs abnormal cases, DRISK IT Android app (available [here] (https://play.google.com/store/apps/details?id=com.driskitapplication.Driskit&hl=en) ), uses it and when you try with older version of Android OS you don't see this, but with latest Android version or newest phones you see this error.

**Comment by BobKnothe** [comment] 2015-12-24 11:06
That's odd because that is almost opposite of what I experienced. Some of the early Android mobile chrome browsers were bad - they did not support all of the events and in the same order as their desktop countparts. Windows mobile was even worst, apple was the only one the function properly. At one point I started to create a helper pluugin just to correct these bugs. Google started to correct chrome and I have not heard this for a couple years so I am surprised this is showing up in the latest version. I have not heard of this app before so I cannot speak to your issues until I have time to evaluate. Hopefully I can check this out over the next couple weeks. 


-------- Original Message --------
Subject: Re: [autoNumeric] automatically doubling numbers when
formatted. (#186)

**Comment by fmiboy** [comment] 2015-12-24 11:10
I see, thanks!
By old, I didn't mean very old devices, but relatively speaking older versions, 4.1 etc they function alright. But I heard it happened few occasion with newest version of Android OS. Maybe they start to use Chromium for later version and maybe there is small bug in here or there..?! I am trying to use Crosswalk to see if it helps, but that's not solution though.

**Comment by BobKnothe** [comment] 2016-01-08 17:42
I cannot replicate or find the issue.

When 4.0 - 4.1 first came out with chrome browser there were many issue bit as the browser was updated I have not heard of any new issue. 

I am going to close this issue for now but if you get more details please open back up.

**Closed by BobKnothe** 2016-01-08 17:42 UTC

**Comment by rubisara** [comment] 2017-06-01 04:19
Version: 2.0.12

I'm able to replicate this issue using samsung phone - chrome browser 58.0.3029.83.
You can only replicate it using a mobile phone. 

Please help

**Comment by AlexandreBonneau** [comment] 2017-06-01 08:17
Hey @rubisara, could you please try to reproduce the bug with the latest version on the `next` branch?

In a few days it will become the next stable version `4.0.0` on `master`.
